---
    environment: production
    address: 127.0.0.1
    user: jhan
    group: jhan
    port: 5000
    pid: /var/run/sslcon/thin-pid
    rackup: /home/jhan/SSL-Converter-Web/config.ru
    log: /home/jhan/SSL-Converter-Web/log/sslcon-log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: false
